### ISSUE TITLE
Version downgrade

### ISSUE THREAD

**Issue by ga58xes** [crossrulz/SerialPortNuggets#1]
Hi, 
could you provide your SerialPortNuggets-VIs for LabVIEW 2017, please?

Thanks for your work!

Best regards, 
Sebastian

**Comment by crossrulz** [comment]
[2016.zip](https://github.com/crossrulz/SerialPortNuggets/files/4871795/2016.zip)
Attached was saved in 2016.  The maps in the actor code will be broken (new in 2019), but the rest should be good.
